"""add base columns

Revision ID: a6a89aaf97bd
Revises: bde178a54c68
Create Date: 2025-11-06 15:11:50.341404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a89aaf97bd'
down_revision: Union[str, Sequence[str], None] = 'bde178a54c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icms')
    op.drop_table('orders')
    op.drop_table('tickets')
    op.drop_table('orders_status')
    op.drop_table('proposals_status')
    op.drop_table('shipments')
    op.drop_table('payments')
    op.drop_table('tickets_status')
    op.drop_table('proposals')
    op.drop_table('users')
    op.drop_table('customers')
    op.drop_table('products')
    op.drop_table('ipi')
    op.drop_table('tax')
    op.drop_table('shipments_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments_status',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('icms_id', sa.INTEGER(), nullable=True),
    sa.Column('ipi_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['icms_id'], ['icms.id'], ),
    sa.ForeignKeyConstraint(['ipi_id'], ['ipi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipi',
    sa.Column('value', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('base_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('tax_id', sa.INTEGER(), nullable=True),
    sa.Column('part_number', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ncm_code', sa.TEXT(), nullable=True),
    sa.Column('unit', sa.TEXT(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('unit_price', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('material', sa.TEXT(), nullable=True),
    sa.Column('origin', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['tax_id'], ['tax.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('tax_id', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.NUMERIC(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('proposal_number', sa.INTEGER(), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['proposals_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_number')
    )
    op.create_table('tickets_status',
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('billing_until', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('tracking_number', sa.TEXT(), nullable=True),
    sa.Column('shipment_date', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['shipments_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals_status',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_status',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_number', sa.INTEGER(), nullable=True),
    sa.Column('opened_at', sa.DATE(), nullable=True),
    sa.Column('closed_at', sa.DATE(), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['tickets_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_id', sa.INTEGER(), nullable=True),
    sa.Column('proposal_id', sa.INTEGER(), nullable=True),
    sa.Column('status_id', sa.INTEGER(), nullable=False),
    sa.Column('shipment_status_id', sa.INTEGER(), nullable=True),
    sa.Column('portal', sa.TEXT(), nullable=True),
    sa.Column('center', sa.TEXT(), nullable=True),
    sa.Column('vale_order_id', sa.INTEGER(), nullable=False),
    sa.Column('besc_order_id', sa.INTEGER(), nullable=True),
    sa.Column('contract_number', sa.TEXT(), nullable=True),
    sa.Column('invoice_number', sa.TEXT(), nullable=True),
    sa.Column('total_value', sa.REAL(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ),
    sa.ForeignKeyConstraint(['shipment_status_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['orders_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vale_order_id')
    )
    op.create_table('icms',
    sa.Column('value', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('rate', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('base_amount', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
