"""add numero_pedido column to pedidos

Revision ID: bde178a54c68
Revises: 
Create Date: 2025-11-01 15:01:10.880772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde178a54c68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos')
    op.drop_table('tributario')
    op.drop_table('propostas')
    op.drop_table('clientes')
    op.drop_table('status_chamado')
    op.drop_table('users')
    op.drop_table('status_expedicao')
    op.drop_table('pagamentos')
    op.drop_table('status_proposta')
    op.drop_table('chamados')
    op.drop_table('status_pedidos')
    op.drop_table('produtos')
    op.drop_table('icms')
    op.drop_table('expedicao')
    op.drop_table('ipi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipi',
    sa.Column('id_ipi', sa.INTEGER(), nullable=True),
    sa.Column('valor', sa.DECIMAL(), nullable=True),
    sa.Column('percentual', sa.DECIMAL(), nullable=True),
    sa.Column('base', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_ipi')
    )
    op.create_table('expedicao',
    sa.Column('id_expedicao', sa.INTEGER(), nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_status'], ['status_expedicao.id_status'], ),
    sa.PrimaryKeyConstraint('id_expedicao')
    )
    op.create_table('icms',
    sa.Column('id_icms', sa.INTEGER(), nullable=True),
    sa.Column('valor', sa.DECIMAL(), nullable=True),
    sa.Column('percentual', sa.DECIMAL(), nullable=True),
    sa.Column('base', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_icms')
    )
    op.create_table('produtos',
    sa.Column('id_produto', sa.INTEGER(), nullable=True),
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('part_number', sa.TEXT(), nullable=True),
    sa.Column('valor_individual', sa.DECIMAL(), nullable=False),
    sa.Column('data_entrada', sa.DATE(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('ncm', sa.TEXT(), nullable=True),
    sa.Column('qtde', sa.INTEGER(), nullable=True),
    sa.Column('material', sa.TEXT(), nullable=True),
    sa.Column('origem', sa.TEXT(), nullable=True),
    sa.Column('id_tributario', sa.INTEGER(), nullable=True),
    sa.Column('unidade', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_tributario'], ['tributario.id_tributario'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('status_pedidos',
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('chamados',
    sa.Column('id_chamado', sa.INTEGER(), nullable=True),
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('numero_chamado', sa.INTEGER(), nullable=True),
    sa.Column('data_abertura', sa.DATE(), nullable=True),
    sa.Column('data_finalizado', sa.DATE(), nullable=True),
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('observacao', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_status'], ['status_chamado.id_status'], ),
    sa.PrimaryKeyConstraint('id_chamado')
    )
    op.create_table('status_proposta',
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('pagamentos',
    sa.Column('id_pagamento', sa.INTEGER(), nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('data_pagamento', sa.DATE(), nullable=True),
    sa.Column('faturar_ate', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.PrimaryKeyConstraint('id_pagamento')
    )
    op.create_table('status_expedicao',
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=False),
    sa.Column('numero_coleta', sa.TEXT(), nullable=True),
    sa.Column('data_coleta', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('users',
    sa.Column('id_user', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('hashed_password', sa.TEXT(), nullable=False),
    sa.Column('company', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('status_chamado',
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('nome', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_table('clientes',
    sa.Column('id_cliente', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('propostas',
    sa.Column('id_proposta', sa.INTEGER(), nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('numero_proposta', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id_status', sa.INTEGER(), nullable=True),
    sa.Column('numero_pedido', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_status'], ['status_proposta.id_status'], ),
    sa.PrimaryKeyConstraint('id_proposta')
    )
    op.create_table('tributario',
    sa.Column('id_tributario', sa.INTEGER(), nullable=True),
    sa.Column('id_icms', sa.INTEGER(), nullable=True),
    sa.Column('id_ipi', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_icms'], ['icms.id_icms'], ),
    sa.ForeignKeyConstraint(['id_ipi'], ['ipi.id_ipi'], ),
    sa.PrimaryKeyConstraint('id_tributario')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.INTEGER(), nullable=True),
    sa.Column('id_cliente', sa.INTEGER(), nullable=False),
    sa.Column('numero_pedido', sa.INTEGER(), nullable=False),
    sa.Column('n_contrato', sa.INTEGER(), nullable=True),
    sa.Column('prazo_entrega', sa.DATE(), nullable=True),
    sa.Column('id_status', sa.INTEGER(), nullable=False),
    sa.Column('data_faturamento', sa.DATE(), nullable=True),
    sa.Column('nota_fiscal', sa.TEXT(), nullable=True),
    sa.Column('valor_total', sa.DECIMAL(), nullable=False),
    sa.Column('centro', sa.TEXT(), nullable=True),
    sa.Column('portal', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_status'], ['status_pedidos.id_status'], ),
    sa.PrimaryKeyConstraint('id_pedido'),
    sa.UniqueConstraint('numero_pedido')
    )
    # ### end Alembic commands ###
