
CREATE TABLE IF NOT EXISTS tax(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    icms_id INTEGER,
    ipi_id INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (icms_id) REFERENCES icms(id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (ipi_id) REFERENCES ipi(id)
        ON UPDATE CASCADE ON DELETE SET NULL
);
